### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ghostbucket16** [JT122406/HungerGames#11]
**Describe the bug**
When using the nether start to start games earlier than the 25 second timer (with more than 1 player) both health and hunger changes from full, down to 2 hearts and 2 bars.

**To Reproduce**
Load into a HungerGames Map and start the game earlier than the default count down, with multiple players.

**Expected behavior**
Hunger and Health drops from full to 2 bars on each.

**Screenshots/Errors**
No errors in the console or on screen.

**Version Info:**
 - **Plugin Version:** 5.2.0
 - **Server Version/Platform** 1.19.2 spigot -- 1.12.2

**Additional context**
If you don't skip the countdown, your health and hunger don't change and the bug doesn't seem to happen.

**Comment by JT122406** [comment]
It changes from full to 2 health?

**Comment by Yomamaeatstoes** [comment]
[18.02 19:59:38] [Server] [ERROR] Could not pass event InventoryCloseEvent to HungerGames v5.2.3
[18.02 19:59:38] [Server] java.lang.NullPointerExceptionCannot invoke "tk.shanebee.hg.game.Game.getChestDropManager()" because "game" is null
[18.02 19:59:38] [Server] 	at tk.shanebee.hg.listeners.ChestDropListener.onInventoryClose(ChestDropListener.java:35) ~[HungerGames-5.2.3.jar:?]
[18.02 19:59:38] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor216.execute(Unknown Source) ~[?:?]
[18.02 19:59:38] [Server] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[18.02 19:59:38] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[18.02 19:59:38] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[18.02 19:59:38] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1534) ~[paper-1.19.2.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3071) ~[?:?]
[18.02 19:59:38] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3064) ~[?:?]
[18.02 19:59:38] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
[18.02 19:59:38] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
[18.02 19:59:38] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
[18.02 19:59:38] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[18.02 19:59:38] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[18.02 19:59:38] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[18.02 19:59:38] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[18.02 19:59:38] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
[18.02 19:59:38] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Yomamaeatstoes** [comment]
[08:52:17] [Server thread/WARN]: §7[§e§lHungerGames§7] §eWARNING: Missing PotionEffectType for '§7PotionEffectType[33, DARKNESS]§e' please let dev know.

**Comment by JT122406** [comment]
Fixed in last update I believe
