### ISSUE TITLE
[BUG] Task #156

### ISSUE THREAD

**Issue by TheMikol** [JT122406/HungerGames#23]
**Describe the bug**
After entering the arena there are errors in the console, the arena does not start and players can walk around and break blocks

**To Reproduce**
1. Create an arena
2 Play a few times with friends
3. Errors in the console

**Screenshots/Errors**
[Server thread/WARN]: [HungerGames] Task #156 for HungerGames v5.2.3 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 23.0. (attribute base value: 20.0, player: TheMikol)
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:112) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at tk.shanebee.hg.tasks.StartingTask.run(StartingTask.java:54) ~[HungerGames-5.2.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:497) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Version Info:**
 - **Plugin Version:** 5.2.3
 - **Server Version/Platform** Fusion 1.19.3 (Paper fork), Java 17

**Additional context**
The problem also occurs when a player enters with half a heart and not a full

**Comment by JT122406** [comment]
Fixed with b261b2dbcdb2273373842a7f1fa3406875b6e169
