### ISSUE TITLE
[BUG] Could not pass event InventoryCloseEvent

### ISSUE THREAD

**Issue by TheMikol** [JT122406/HungerGames#26]
**Describe the bug**
Collision with other minigames plugins (any minigame using chest/ex. SkyWars X, KitBattle, Wizards etc.)

**To Reproduce**
 1. Play another game ex. SkyWars
 2. Errors in the console

**Screenshots/Errors**
[Server thread/ERROR]: Could not pass event InventoryCloseEvent to HungerGames v5.2.3
java.lang.NullPointerException: Cannot invoke "tk.shanebee.hg.game.Game.getChestDropManager()" because "game" is null
	at tk.shanebee.hg.listeners.ChestDropListener.onInventoryClose(ChestDropListener.java:35) ~[HungerGames-5.2.3.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[Fusion-API-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Fusion-API-1.19.3-R0.1-SNAPSHOT.jar:git-Fusion-"754f61a"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Fusion-API-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[Fusion-API-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1563) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3048) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3041) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Version Info:**
 - **Plugin Version:** 5.2.3
 - **Server Version/Platform:** Fusion 1.19.3 (Paper fork), Java 17

**Comment by Troublemaker141** [comment]
This error happens every time you close an inventory created by an outher plugin.

**Comment by sovtec** [comment]
> **Describe the bug**
> 
> Collision with other minigames plugins (any minigame using chest/ex. SkyWars X, KitBattle, Wizards etc.)
> 
> 
> 
> **To Reproduce**
> 
>  1. Play another game ex. SkyWars
> 
>  2. Errors in the console
> 
> 
> 
> **Screenshots/Errors**
> 
> [Server thread/ERROR]: Could not pass event InventoryCloseEvent to HungerGames v5.2.3
> 
> java.lang.NullPointerException: Cannot invoke "tk.shanebee.hg.game.Game.getChestDropManager()" because "game" is null
> 
> 	at tk.shanebee.hg.listeners.ChestDropListener.onInventoryClose(ChestDropListener.java:35) ~[HungerGames-5.2.3.jar:?]
> 
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor272.execute(Unknown Source) ~[?:?]
> 
> 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[Fusion-API-1.19.3-R0.1-SNAPSHOT.jar:?]
> 
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Fusion-API-1.19.3-R0.1-SNAPSHOT.jar:git-Fusion-"754f61a"]
> 
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Fusion-API-1.19.3-R0.1-SNAPSHOT.jar:?]
> 
> 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[Fusion-API-1.19.3-R0.1-SNAPSHOT.jar:?]
> 
> 	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1563) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3048) ~[?:?]
> 
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3041) ~[?:?]
> 
> 	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
> 
> 	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
> 
> 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
> 
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
> 
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
> 
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
> 
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
> 
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[fusion-1.19.3.jar:git-Fusion-"754f61a"]
> 
> 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
> 
> 
> 
> **Version Info:**
> 
>  - **Plugin Version:** 5.2.3
> 
>  - **Server Version/Platform:** Fusion 1.19.3 (Paper fork), Java 17

https://github.com/sabre3/HungerGames

**Comment by JT122406** [comment]
Taking a look at this today

**Comment by JT122406** [comment]
Could y'all try this and lmk

**Comment by JT122406** [comment]
[hungergames.zip](https://github.com/JT122406/HungerGames/files/11163189/hungergames.zip)
Just unzip and put jar in
