### ISSUE TITLE
[BUG] Doesnt start

### ISSUE THREAD

**Issue by Fingerious** [JT122406/HungerGames#34]
I can't find the version I need, can you provide a link?

[19:31:58 ERROR]: Could not load 'plugins\HungerGames-5.2.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: tk/shanebee/hg/HG has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:279) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_371]
Caused by: java.lang.UnsupportedClassVersionError: tk/shanebee/hg/HG has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_371]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_371]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_371]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_371]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_371]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_371]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_371]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1171]
        ... 7 more

**Comment by Fingerious** [comment]
> I can't find the version I need, can you provide a link?
> 
> [19:31:58 ERROR]: Could not load 'plugins\HungerGames-5.2.4.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: tk/shanebee/hg/HG has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:279) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171] at java.lang.Thread.run(Unknown Source) [?:1.8.0_371] Caused by: java.lang.UnsupportedClassVersionError: tk/shanebee/hg/HG has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_371] at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_371] at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_371] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[patched_1.16.5.jar:git-Purpur-1171] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_371] at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_371] at java.lang.Class.forName0(Native Method) ~[?:1.8.0_371] at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_371] at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Purpur-1171] at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1171] ... 7 more

purpur 1.16.5
